#define SERVER_URL "http://10.3.41.39:8000"

#define PROTO_SSID "PlantPalConfig"
#define PROTO_PASSWORD "plantpal"
#define HOSTNAME "PlantPal"

#define MOISTURE_SENSOR_PIN 36
#define FLOW_METER_PIN 2
#define WATER_PUMP_PIN 14

#define MOISTURE_NONE 2660
#define MOISTURE_WET 930
#define IRRIGATION_THRESHOLD_PERCENTAGE 50
#define IRRIGATION_AMOUNT 1000
#define CALIBRATION_FACTOR 4.5

#define INTERVAL 1000
